# Generated by Django 3.1.5 on 2021-01-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
