# Generated by Django 3.1.5 on 2021-01-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_produto_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
